name: Proxy Downloader
on:
  repository_dispatch:
    types: [proxy_request]
jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Download File
        run: |
          curl -L "${{ github.event.client_payload.url }}" -o "downloaded_file"
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: downloaded_file
          path: downloaded_file
